compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_processes: 8 # Or whatever number of GPUs you specified (e.g., 4)
num_machines: 1
main_process_ip: null
main_process_port: null
machine_rank: 0
gpu_ids: null # Accelerate will typically auto-detect and use available GPUs
mixed_precision: "bf16" # Or "bf16", or "no" if you chose not to use mixed precision
use_cpu: false
deepspeed_config: {} # Will be populated if DeepSpeed is enabled
fsdp_config: {} # Will be populated if FSDP is enabled
megatron_lm_config: {} # Will be populated if Megatron-LM is enabled