# Model arguments
model_name_or_path: HuggingFaceTB/SmolLM-1.7B
teacher_model_name_or_path: HuggingFaceTB/SmolLM-1.7B
with_distill: false
mla_layers: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
init_with_svd: true
decontaminate: true
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
dataset_mixer:
  dataset/fineweb-edu-dedup: 0.02
  dataset/cosmopedia-v2: 0.02
  dataset/python-edu: 0.02
dataset_splits:
- train
preprocessing_num_workers: 64 

# Trainer config
bf16: true
do_eval: False
evaluation_strategy: epoch
gradient_accumulation_steps: 2
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 8.0e-05
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: 15259
max_grad_norm: 1.0
num_train_epochs: -1
output_dir: checkpoints/MlaInLlama_1.7B_kv480_pretrain_1.7bt
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 12
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 2000
save_total_limit: 1
seed: 42
warmup_ratio: 0.01
kl_weight: 1.0
ce_weight: 0.0

# MLA configs
q_lora_rank: 2048
qk_rope_head_dim: 32
kv_lora_rank: 480
v_head_dim: 64
qk_nope_head_dim: 32
freeze_non_mla: false
use_lora_layer_norm: false